rest: gunicorn -c gunicorn_config.py wsgi
wamp: python3 -u ws.py
work: celery -A worker worker
publish: celery -A worker -Q "${SUPERDESK_CELERY_PREFIX}publish" worker
beat: celery -A worker beat --pid=
