rest: gunicorn -c gunicorn_config.py wsgi
wamp: python3 -u ws.py
work: celery -A worker -X "${SUPERDESK_CELERY_PREFIX}publish,${SUPERDESK_CELERY_PREFIX}publish_priority"   worker
publish: celery -A worker -Q "${SUPERDESK_CELERY_PREFIX}publish" worker
capi: gunicorn -c gunicorn_config.py content_api.wsgi
papi: gunicorn -c gunicorn_config.py prod_api.wsgi
beat: celery -A worker beat
publish_priority: celery -A worker -Q "${SUPERDESK_CELERY_PREFIX}publish_priority" worker
