rest: gunicorn -c gunicorn_config.py wsgi
wamp: python3 -u ws.py
work: celery -A worker -Q default,expiry,legal  worker
publish: celery -A worker -Q publish  worker
beat: celery -A worker beat --pid=
