name: "CI"

on:
  [push, pull_request]

jobs:

  server:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: server

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: 3.6

    - run: sudo apt-get -y install libxmlsec1-dev

    - run: docker-compose -f ../.github/docker-compose.yml up -d

    - run: |
        python -m pip install --upgrade pip wheel setuptools
        pip install -r dev-requirements.txt

    - run: flake8

    - run: nosetests

    - run: behave ./features/ --format progress2 --logging-level ERROR

    - run: python manage.py app:initialize_data


  client:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: client

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - run: npm install --no-audit

    - run: npm test

    - run: npm run build
